namespace octo_fiesta.Models.Settings;

/// <summary>
/// Configuration for the Qobuz downloader and metadata service
/// </summary>
public class QobuzSettings
{
    /// <summary>
    /// Qobuz user authentication token
    /// Obtained from browser's localStorage after logging into play.qobuz.com
    /// </summary>
    public string? UserAuthToken { get; set; }
    
    /// <summary>
    /// Qobuz user ID
    /// Obtained from browser's localStorage after logging into play.qobuz.com
    /// </summary>
    public string? UserId { get; set; }
    
    /// <summary>
    /// Preferred audio quality: FLAC, MP3_320, MP3_128
    /// If not specified or unavailable, the highest available quality will be used.
    /// </summary>
    public string? Quality { get; set; }

    /// <summary>
    /// Optional Qobuz App ID. When set together with <see cref="AppSecret"/>, these are
    /// used directly instead of scraping the play.qobuz.com web bundle.
    /// A Qobuz user_auth_token is only valid with the app_id that issued it, so this is
    /// required to use a token that was generated by an app other than the web player
    /// (e.g. the desktop/mobile apps). Leave empty to keep the default behaviour.
    /// </summary>
    public string? AppId { get; set; }

    /// <summary>
    /// Optional Qobuz App Secret used to sign download requests.
    /// Required when <see cref="AppId"/> is set.
    /// </summary>
    public string? AppSecret { get; set; }
}
