using octo_fiesta.Services.Common;
using Xunit;

namespace octo_fiesta.Tests;

public class QualityHelperTests
{
    [Theory]
    // Legacy downloads (null quality) should always upgrade
    [InlineData(null, "FLAC", true)]
    [InlineData(null, "MP3_320", true)]
    [InlineData(null, "MP3_128", true)]
    [InlineData(null, "AAC_320", true)]
    [InlineData(null, "AAC_96", true)]
    // AAC_64 (lowest) to higher quality
    [InlineData("AAC_64", "AAC_96", true)]
    [InlineData("AAC_64", "MP3_128", true)]
    [InlineData("AAC_64", "MP3_192", true)]
    [InlineData("AAC_64", "AAC_192", true)]
    [InlineData("AAC_64", "AAC_256", true)]
    [InlineData("AAC_64", "AAC_320", true)]
    [InlineData("AAC_64", "MP3_320", true)]
    [InlineData("AAC_64", "FLAC", true)]
    [InlineData("AAC_64", "FLAC_16", true)]
    [InlineData("AAC_64", "FLAC_24", true)]
    [InlineData("AAC_64", "FLAC_24_LOW", true)]
    [InlineData("AAC_64", "FLAC_24_HIGH", true)]
    // AAC_96 to higher quality
    [InlineData("AAC_96", "MP3_128", true)]
    [InlineData("AAC_96", "MP3_192", true)]
    [InlineData("AAC_96", "AAC_192", true)]
    [InlineData("AAC_96", "AAC_256", true)]
    [InlineData("AAC_96", "AAC_320", true)]
    [InlineData("AAC_96", "MP3_320", true)]
    [InlineData("AAC_96", "FLAC", true)]
    [InlineData("AAC_96", "FLAC_16", true)]
    [InlineData("AAC_96", "FLAC_24", true)]
    [InlineData("AAC_96", "FLAC_24_LOW", true)]
    [InlineData("AAC_96", "FLAC_24_HIGH", true)]
    // MP3_128 to higher quality
    [InlineData("MP3_128", "MP3_192", true)]
    [InlineData("MP3_128", "AAC_192", true)]
    [InlineData("MP3_128", "AAC_256", true)]
    [InlineData("MP3_128", "AAC_320", true)]
    [InlineData("MP3_128", "MP3_320", true)]
    [InlineData("MP3_128", "FLAC", true)]
    [InlineData("MP3_128", "FLAC_16", true)]
    [InlineData("MP3_128", "FLAC_24", true)]
    [InlineData("MP3_128", "FLAC_24_LOW", true)]
    [InlineData("MP3_128", "FLAC_24_HIGH", true)]
    // MP3_192 to higher quality
    [InlineData("MP3_192", "AAC_192", true)]
    [InlineData("MP3_192", "AAC_256", true)]
    [InlineData("MP3_192", "AAC_320", true)]
    [InlineData("MP3_192", "MP3_320", true)]
    [InlineData("MP3_192", "FLAC", true)]
    [InlineData("MP3_192", "FLAC_16", true)]
    [InlineData("MP3_192", "FLAC_24", true)]
    [InlineData("MP3_192", "FLAC_24_LOW", true)]
    [InlineData("MP3_192", "FLAC_24_HIGH", true)]
    // AAC_192 to higher quality
    [InlineData("AAC_192", "AAC_256", true)]
    [InlineData("AAC_192", "AAC_320", true)]
    [InlineData("AAC_192", "MP3_320", true)]
    [InlineData("AAC_192", "FLAC", true)]
    [InlineData("AAC_192", "FLAC_16", true)]
    [InlineData("AAC_192", "FLAC_24", true)]
    [InlineData("AAC_192", "FLAC_24_LOW", true)]
    [InlineData("AAC_192", "FLAC_24_HIGH", true)]
    // AAC_256 to higher quality
    [InlineData("AAC_256", "AAC_320", true)]
    [InlineData("AAC_256", "MP3_320", true)]
    [InlineData("AAC_256", "FLAC", true)]
    [InlineData("AAC_256", "FLAC_16", true)]
    [InlineData("AAC_256", "FLAC_24", true)]
    [InlineData("AAC_256", "FLAC_24_LOW", true)]
    [InlineData("AAC_256", "FLAC_24_HIGH", true)]
    // AAC_320 to higher quality
    [InlineData("AAC_320", "FLAC", true)]
    [InlineData("AAC_320", "FLAC_16", true)]
    [InlineData("AAC_320", "FLAC_24", true)]
    [InlineData("AAC_320", "FLAC_24_LOW", true)]
    [InlineData("AAC_320", "FLAC_24_HIGH", true)]
    [InlineData("MP3_320", "FLAC", true)]
    [InlineData("MP3_320", "FLAC_16", true)]
    [InlineData("MP3_320", "FLAC_24", true)]
    [InlineData("MP3_320", "FLAC_24_LOW", true)]
    [InlineData("MP3_320", "FLAC_24_HIGH", true)]
    // Lossless to higher options
    [InlineData("FLAC", "FLAC_24", true)]
    [InlineData("FLAC", "FLAC_24_LOW", true)]
    [InlineData("FLAC", "FLAC_24_HIGH", true)]
    [InlineData("FLAC_16", "FLAC_24", true)]
    [InlineData("FLAC_16", "FLAC_24_LOW", true)]
    [InlineData("FLAC_16", "FLAC_24_HIGH", true)]
    [InlineData("FLAC_24", "FLAC_24_HIGH", true)]
    [InlineData("FLAC_24_LOW", "FLAC_24_HIGH", true)]
    // Same quality should not upgrade
    [InlineData("AAC_64", "AAC_64", false)]
    [InlineData("AAC_96", "AAC_96", false)]
    [InlineData("MP3_128", "MP3_128", false)]
    [InlineData("MP3_192", "MP3_192", false)]
    [InlineData("AAC_192", "AAC_192", false)]
    [InlineData("AAC_256", "AAC_256", false)]
    [InlineData("AAC_320", "AAC_320", false)]
    [InlineData("AAC_320", "MP3_320", false)]   // Same level
    [InlineData("MP3_320", "AAC_320", false)]
    [InlineData("MP3_320", "MP3_320", false)]
    [InlineData("FLAC", "FLAC", false)]
    [InlineData("FLAC", "FLAC_16", false)]  // Same level
    [InlineData("FLAC_16", "FLAC", false)]
    [InlineData("FLAC_16", "FLAC_16", false)]
    [InlineData("FLAC_24", "FLAC_24", false)]
    [InlineData("FLAC_24", "FLAC_24_LOW", false)]
    [InlineData("FLAC_24_LOW", "FLAC_24", false)]
    [InlineData("FLAC_24_LOW", "FLAC_24_LOW", false)]
    [InlineData("FLAC_24_HIGH", "FLAC_24_HIGH", false)]
    // Lower quality should not upgrade
    [InlineData("AAC_96", "AAC_64", false)]
    [InlineData("MP3_128", "AAC_64", false)]
    [InlineData("MP3_128", "AAC_96", false)]
    [InlineData("MP3_192", "AAC_64", false)]
    [InlineData("MP3_192", "AAC_96", false)]
    [InlineData("MP3_192", "MP3_128", false)]
    [InlineData("AAC_192", "AAC_64", false)]
    [InlineData("AAC_192", "AAC_96", false)]
    [InlineData("AAC_192", "MP3_128", false)]
    [InlineData("AAC_192", "MP3_192", false)]
    [InlineData("AAC_256", "AAC_64", false)]
    [InlineData("AAC_256", "AAC_96", false)]
    [InlineData("AAC_256", "MP3_128", false)]
    [InlineData("AAC_256", "MP3_192", false)]
    [InlineData("AAC_256", "AAC_192", false)]
    [InlineData("AAC_320", "AAC_64", false)]
    [InlineData("AAC_320", "AAC_96", false)]
    [InlineData("AAC_320", "MP3_128", false)]
    [InlineData("AAC_320", "MP3_192", false)]
    [InlineData("AAC_320", "AAC_192", false)]
    [InlineData("AAC_320", "AAC_256", false)]
    [InlineData("MP3_320", "AAC_64", false)]
    [InlineData("MP3_320", "AAC_96", false)]
    [InlineData("MP3_320", "MP3_128", false)]
    [InlineData("MP3_320", "MP3_192", false)]
    [InlineData("MP3_320", "AAC_192", false)]
    [InlineData("MP3_320", "AAC_256", false)]
    [InlineData("FLAC", "AAC_64", false)]
    [InlineData("FLAC", "AAC_96", false)]
    [InlineData("FLAC", "MP3_128", false)]
    [InlineData("FLAC", "MP3_192", false)]
    [InlineData("FLAC", "AAC_192", false)]
    [InlineData("FLAC", "AAC_256", false)]
    [InlineData("FLAC", "AAC_320", false)]
    [InlineData("FLAC", "MP3_320", false)]
    [InlineData("FLAC_16", "AAC_64", false)]
    [InlineData("FLAC_16", "AAC_96", false)]
    [InlineData("FLAC_16", "MP3_128", false)]
    [InlineData("FLAC_16", "MP3_192", false)]
    [InlineData("FLAC_16", "AAC_192", false)]
    [InlineData("FLAC_16", "AAC_256", false)]
    [InlineData("FLAC_16", "AAC_320", false)]
    [InlineData("FLAC_16", "MP3_320", false)]
    [InlineData("FLAC_24", "AAC_64", false)]
    [InlineData("FLAC_24", "AAC_96", false)]
    [InlineData("FLAC_24", "MP3_128", false)]
    [InlineData("FLAC_24", "MP3_192", false)]
    [InlineData("FLAC_24", "AAC_192", false)]
    [InlineData("FLAC_24", "AAC_256", false)]
    [InlineData("FLAC_24", "AAC_320", false)]
    [InlineData("FLAC_24", "MP3_320", false)]
    [InlineData("FLAC_24", "FLAC", false)]
    [InlineData("FLAC_24", "FLAC_16", false)]
    [InlineData("FLAC_24_LOW", "AAC_64", false)]
    [InlineData("FLAC_24_LOW", "AAC_96", false)]
    [InlineData("FLAC_24_LOW", "MP3_128", false)]
    [InlineData("FLAC_24_LOW", "MP3_192", false)]
    [InlineData("FLAC_24_LOW", "AAC_192", false)]
    [InlineData("FLAC_24_LOW", "AAC_256", false)]
    [InlineData("FLAC_24_LOW", "AAC_320", false)]
    [InlineData("FLAC_24_LOW", "MP3_320", false)]
    [InlineData("FLAC_24_LOW", "FLAC", false)]
    [InlineData("FLAC_24_LOW", "FLAC_16", false)]
    [InlineData("FLAC_24_HIGH", "AAC_64", false)]
    [InlineData("FLAC_24_HIGH", "AAC_96", false)]
    [InlineData("FLAC_24_HIGH", "MP3_128", false)]
    [InlineData("FLAC_24_HIGH", "MP3_192", false)]
    [InlineData("FLAC_24_HIGH", "AAC_192", false)]
    [InlineData("FLAC_24_HIGH", "AAC_256", false)]
    [InlineData("FLAC_24_HIGH", "AAC_320", false)]
    [InlineData("FLAC_24_HIGH", "MP3_320", false)]
    [InlineData("FLAC_24_HIGH", "FLAC", false)]
    [InlineData("FLAC_24_HIGH", "FLAC_16", false)]
    [InlineData("FLAC_24_HIGH", "FLAC_24", false)]
    [InlineData("FLAC_24_HIGH", "FLAC_24_LOW", false)]
    public void ShouldUpgrade_ReturnsExpectedResult(string? existingQuality, string targetQuality, bool expected)
    {
        var result = QualityHelper.ShouldUpgrade(existingQuality, targetQuality);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("AAC_64", null)]
    [InlineData("AAC_64", "")]
    [InlineData("MP3_128", null)]
    [InlineData("MP3_128", "")]
    [InlineData("FLAC", null)]
    [InlineData("FLAC", "")]
    public void ShouldUpgrade_WithNullOrEmptyTarget_ReturnsFalse(string? existingQuality, string? targetQuality)
    {
        var result = QualityHelper.ShouldUpgrade(existingQuality, targetQuality);
        Assert.False(result);
    }

    [Theory]
    [InlineData("AAC_64", 0)]
    [InlineData("AAC_96", 1)]
    [InlineData("MP3_128", 2)]
    [InlineData("MP3_192", 3)]
    [InlineData("AAC_192", 4)]
    [InlineData("AAC_256", 5)]
    [InlineData("AAC_320", 6)]
    [InlineData("MP3_320", 6)]
    [InlineData("FLAC", 7)]
    [InlineData("FLAC_16", 7)]
    [InlineData("FLAC_24", 8)]
    [InlineData("FLAC_24_LOW", 8)]
    [InlineData("FLAC_24_HIGH", 9)]
    [InlineData("unknown", 0)]
    [InlineData(null, 0)]
    [InlineData("", 0)]
    public void GetQualityLevel_ReturnsExpectedLevel(string? quality, int expectedLevel)
    {
        var result = QualityHelper.GetQualityLevel(quality);
        Assert.Equal(expectedLevel, result);
    }
}
